//TODO: add the optional prayers
export const prayers: Record<string, string> = {
	SignOfCross:
		' In the name of the Father, and of the Son, and of the Holy Spirit.\n Amen.',
	ApostlesCreed:
		' I believe in God, the Father almighty creator of heaven and earth and in Jesus Christ,\n His only Son, our Lord, who was conceived by the Holy Spirit,\n born of the Virgin Mary, suffered under Pontius Pilate,\n was crucified, died, and was buried.\n He descended into hell. On the third day he rose again from the dead.\n He ascended into heaven and is seated at the right hand of God, the Father almighty;\n from there he will come to judge the living and the dead.\n I believe in the Holy Spirit, the Holy Catholic Church, the communion of saints,\n the forgiveness of sins, the resurrection of the body, and the life everlasting.\n Amen.',
	OurFather:
		' Our Father, who art in heaven hallowed be thy name;\n thy kingdom come; thy will be done on earth as it is in heaven.\n Give us this day our daily bread and forgive us our trespasses\n as we forgive those who trespass against us;\n and lead us not into temptation, but deliver us from evil.\n Amen.',
	HailMary:
		' Hail Mary, full of grace. The Lord is with thee.\n Blessed art thou amongst women, And blessed is the fruit of thy womb, Jesus.\n Holy Mary, Mother of God, Pray for us sinners, Now and at the hour of our death.\n Amen.',
	GloryBe:
		' Glory be to the Father, and to the Son, and to the Holy Spirit.\n As it was in the beginning, is now, and ever shall be, world without end.\n Amen.',
	OhMyJesus:
		' O my Jesus, forgive us of our sins. Save us from the fires of hell.\n Lead all souls into heaven, especially those in most need of thy mercy.\n Amen.',
	HailHolyQueen:
		' Hail Holy Queen, Mother of Mercy, our Life, our Sweetness, and our hope.\n To thee do we cry, poor banished children of Eve.\n To thee do we send up our sighs, mourning and weeping in this vale of tears.\n Turn then most gracious advocate, Thine eyes of mercy toward us, and after this,\n our exile, show unto us, the blessed fruit of thy womb, Jesus.\n O clement, O loving, O sweet Virgin Mary.\n Pray for us O Holy Mother of God, That we may be made worthy of the promises of Christ.\n Amen.',
	FinalPrayer:
		' Let us pray. O God, whose only begotten Son, by His life, death, and resurrection,\n has purchased for us the rewards of eternal life, grant, we beseech Thee,\n that meditating upon these mysteries of the Most Holy Rosary of the Blessed Virgin Mary,\n we may imitate what they contain and obtain what they promise, through the same Christ Our Lord.\n Amen.',
};

//TODO: Add sundays of advent and christmas - Joyful, sundays of Lent - Sorrowful
//thursdays joyful if Luminous is not desired, Saturdays Glorious if thursday is joyful
export const dayNames: Record<string, string> = {
	Monday: 'Joyful',
	Tuesday: 'Sorrowful',
	Wednesday: 'Glorious',
	Thursday: 'Luminous',
	Friday: 'Sorrowful',
	Saturday: 'Joyful',
	Sunday: 'Glorious',
};

export const mysteries: Record<string, string> = {
	Joyful: {
		1: {
			name: 'The Annunciation',
			description: 'The First Joyful Mystery – Mary is Chosen Mother of God',
			meditation: 'Obedience',
			1: 'The time for the Incarnation is at hand.',
			2: 'Of all women God prepared Mary from her conception to be the Mother of the Incarnate Word.',
			3: 'The Angel Gabriel announces: “Hail, full of grace! The Lord is with thee.”',
			4: 'Mary wonders at this salutation.',
			5: 'The Angel assures her: “Fear not . . . you shall conceive in your womb, and give birth to a Son.”',
			6: 'Mary is troubled for she has made a vow of virginity.',
			7: 'The Angel answers that she will conceive by the power of the Holy Spirit,\n and her Son will be called the Son of God.',
			8: 'The Incarnation awaits Mary’s consent.',
			9: 'Mary answers: “Behold the handmaid of the Lord. Be it done unto me according to your word.”',
			10: 'The Word was made flesh and dwelt among us',
		},
		2: {
			name: 'The Visitation',
			description: 'The Second Joyful Mystery – Mary Visits Elizabeth',
			meditation: 'Love Others',
			1: 'Mary’s cousin Elizabeth conceived a son in her old age… for nothing is impossible with God.',
			2: 'Charity prompts Mary to hasten to visit Elizabeth in the hour of her need.',
			3: 'The journey to Elizabeth’s home is about eighty miles requiring four or five days.',
			4: 'Though long and arduous, the journey is joyous, for Mary bears with her the Incarnate Word.',
			5: 'At Mary’s salutation, John the Baptist is sanctified in his mother’s womb.',
			6: 'Elizabeth exclaims: “Blessed are you among women, and blessed is the fruit of your womb.”',
			7: '“How have I deserved that the mother of my Lord should come to me?”',
			8: '“Blessed is she who believed that the Lord’s words to her would be fulfilled.”',
			9: 'Mary replies: “My soul proclaims the greatness of the Lord,\n and my spirit finds joy in God my Savior.”',
			10: 'Mary serves her cousin in all humility for three months until the birth of John the Baptist.',
		},
		3: {
			name: 'The Nativity',
			description: 'The Third Joyful Mystery – Jesus is Born',
			meditation: 'Poverty',
			1: 'Joseph and Mary go to Bethlehem to comply with the decree of Caesar Augustus.',
			2: 'The hour for Mary to give birth is near, but there is no room in the inn.',
			3: 'In the stillness of the night, the Savior is born in a cave, Mary remaining a Virgin.',
			4: 'She wraps Him in swaddling clothes and lays Him in a manger.',
			5: 'In unspeakable joy Mary gathers to her bosom the Flower of her virginity.',
			6: 'Jesus enters the world in poverty to teach the lesson of detachment from earthly things.',
			7: 'The angel announces to the shepherds:\n “Today there is born to you in the town of David a Savior, Who is Christ the Lord.”',
			8: 'The angelic chorus sing: “Glory to God in the highest, and peace to His people on earth.”',
			9: 'The shepherds come to the stable to pay homage to the Infant Jesus.',
			10: 'The Magi come to adore the Holy Child and offer Him gifts.',
		},
		4: {
			name: 'The Presentation in the Temple',
			description: 'The Fourth Joyful Mystery – Jesus is Presented to God',
			meditation: 'Humility',
			1: 'Observing the law of Moses they take Jesus to the Temple to present Him to the Lord.',
			2: 'According to the Law the firstborn male child of every family should be consecrated to the Lord.',
			3: 'Mary offers her Son to the Father, then ransoms Him back at the price paid by the poor.',
			4: 'Jesus is not subject to the law of Moses, yet to teach obedience, submits to it.',
			5: 'Mary is not subject to the law of purification, yet in humility she submits to it.',
			6: 'God had revealed to Simeon that he would not see death until he had seen the Messiah.',
			7: 'Recognizing the Child, he prays:\n “Now you can dismiss your servant in peace. You have fulfilled your word.”',
			8: '“This Child is destined to be the downfall and rise of many in Israel,\n a sign that will be opposed.”',
			9: 'And to Mary Simeon reveals: “And your own soul a sword shall pierce.”',
			10: 'After they fulfill all the Law requires they return to Nazareth.',
		},
		5: {
			name: 'The Finding in the Temple',
			description: 'The Fifth Joyful Mystery – Finding Jesus in the Temple',
			meditation: 'Joy in Finding Jesus',
			1: 'When Jesus is twelve years old, He goes with His parents to Jerusalem for the feast of the Passover.',
			2: 'After the feast of the Passover, Joseph and Mary unknowingly set out for Nazareth without Jesus.',
			3: 'At the end of the first day’s journey they discover Jesus is missing.',
			4: 'His parents return immediately looking for Him.',
			5: 'This loss causes grief and anxiety beyond our understanding to the hearts of Mary and Joseph.',
			6: 'On the third day, they find Jesus in the Temple among the Doctors who were astonished at His wisdom.',
			7: 'Mary: “Son, why have you done this to us? Your father and I have been searching for You in sorrow.”',
			8: 'Jesus: “Why did you search for Me? Did you not know that I must be about My Father’s business?”',
			9: 'Jesus goes down with them to Nazareth, and is subject to them.',
			10: 'Mary keeps all these things in her heart.',
		},
	},
	Sorrowful: {
		1: {
			name: 'The Agony in the Garden',
			description: 'The First Sorrowful Mystery – The Agony in the Garden',
			meditation: 'Sorrow for Sin',
			1: 'Jesus comes with his disciples to Gethsemane: “Stay here, while I go yonder and pray.”',
			2: 'Entering the garden with Peter, James, and John, Jesus prays, “My soul is sorrowful unto death.”',
			3: 'Jesus sees the sins of all mankind, whose guilt He has taken upon Himself.',
			4: 'He sees the wrath of the Father which His sufferings must appease.',
			5: 'So great is his anguish that His sweat becomes as drops of blood falling to the ground.',
			6: 'An angel appears to Him from heaven to strengthen Him.',
			7: '“Father, if it be possible, let this cup pass from Me; yet, not My will but Yours be done.”',
			8: 'Finding the disciples asleep: “Could you not watch one hour with me?”',
			9: 'Jesus is betrayed by Judas, cruelly bound and led away.',
			10: 'Father, by the merits of the agony of Jesus in the Garden, have mercy on us and on the whole world.',
		},
		2: {
			name: 'The Scourging at the Pillar',
			description: 'The Second Sorrowful Mystery – The Scourging at the Pillar',
			meditation: 'Purity',
			1: 'Jesus is taken before the High Priest where He is falsely accused, buffeted and insulted.',
			2: 'The Jewish leaders take Jesus before Pilate, for only he can impose the death penalty.',
			3: 'The robber, Barabbas, is preferred to Jesus.',
			4: 'Pilate can “find no cause in Him”, yet to appease the Jews, he orders Jesus to be scourged.',
			5: 'The scourge is made of leather thongs to which are attached small sharp bones.',
			6: 'Jesus is bound to a pillar and cruelly scourged until His whole body is covered with deep wounds.',
			7: 'The Lamb of God offers His suffering for the sins of mankind.',
			8: 'Jesus suffers so much in His sacred flesh to satisfy, especially, for sins of the flesh.',
			9: 'The prophecy of Isaiah is fulfilled:\n “He was wounded for our iniquities, He was bruised for our sins.”',
			10: 'Father, by the merits of Jesus in this painful scourging, have mercy on us and on the whole world.',
		},
		3: {
			name: 'The Crowning with Thorns',
			description: 'The Third Sorrowful Mystery – The Crowning With Thorns',
			meditation: 'Courage',
			1: 'Pilate asks, “Are You a king?” Jesus answers: “I am a King, but My kingdom is not of this world.”',
			2: 'In the praetorium, the soldiers place an old purple robe on Jesus in mockery of His claim to be a king.',
			3: 'They fashion a crown out of thorns, and forcefully press it down upon His head.',
			4: 'In His bound hands they place a reed, as a sceptre, in mockery of His kingship.',
			5: 'Kneeling before Him in derision, they spit on Him, and cry out: “Hail, King of the Jews!”',
			6: 'Taking the reed from His hand they strike Him on the head, driving the thorns more deeply into His scalp.',
			7: 'Pilate brings Jesus before the people, hoping His pitiful sight will soften them: “Behold the man!”',
			8: 'Their response: “Crucify Him! Crucify Him!”',
			9: 'Our Blessed Lord submitted to this terrible humiliation to make reparation for our pride.',
			10: 'Father, by the merits of this painful humiliation, have mercy on us and on the whole world.',
		},
		4: {
			name: 'The Carrying of the Cross',
			description: 'The Fourth Sorrowful Mystery – The Carrying of the Cross',
			meditation: 'Patience',
			1: 'One condemned to death by crucifixion is forced to carry the cross to the place of execution.',
			2: 'The suffering of Jesus is intense as the cross is laid on His bruised and wounded back and shoulders.',
			3: 'Weak and exhausted from loss of blood, lack of food and rest, Jesus falls three times under the cross.',
			4: 'Jesus meets His afflicted Mother causing untold anguish in the Hearts of Son and Mother.',
			5: 'The countenance of Jesus is disfigured with blood and sweat, with dust and spittle.',
			6: 'Veronica wipes His face, leaving on her towel the image of His countenance.',
			7: 'Fearing that Jesus might die on the way, the soldiers force Simon of Cyrene to carry the cross behind Jesus.',
			8: 'Jesus speaks to weeping women: “Weep not for Me, but for yourselves and your children.”',
			9: '“If anyone is to be My disciple, let him take up his cross and follow Me.”',
			10: 'Father, by the merits of this painful journey to Calvary, have mercy on us and on the whole world.',
		},
		5: {
			name: 'The Crucifixion',
			description:
				'The Fifth Sorrowful Mystery – The Crucifixion and Death of Jesus',
			meditation: 'Perseverence',
			1: 'The hands and feet of Jesus are nailed to the cross in the presence of His afflicted Mother.',
			2: '“Father, forgive them for they know not what they do.”',
			3: '“This day you will be with Me in paradise.”',
			4: '“Woman, behold your son. Son, behold your Mother.”',
			5: '“My God, My God, why have You forsaken Me?”',
			6: '“I thirst.”',
			7: '“It is finished.”',
			8: '“Father, into Your hands I commend My spirit.”',
			9: 'The side of Jesus is pierced with a lance. His body is taken down and placed in the arms of His Mother.',
			10: 'Father, by the merits of the crucifixion and death of Jesus, have mercy on us and on the whole world.',
		},
	},
	Glorious: {
		1: {
			name: 'The Resurrection',
			description: 'The First Glorious Mystery – The Resurrection of Jesus',
			meditation: 'Faith',
			1: 'The body of Jesus is placed in the tomb on the evening of Good Friday.',
			2: 'His soul descends into the realm of the dead to announce to the Just the tidings of their redemption.',
			3: 'Fearing the body of Jesus will be taken, the chief priests place guards at the tomb.',
			4: 'On the third day Jesus rises from the dead, glorious and immortal.',
			5: 'The earth quakes as the angel rolls back the stone, the guards flee in terror.',
			6: 'The holy women coming to anoint the body of Jesus are amazed and frightened to find the tomb open.',
			7: 'An angel calms their fears: “He is not here. He has risen as He said.”',
			8: 'Jesus appears to Mary Magdalen and Peter and two disciples on the way to Emmaus.',
			9: 'That evening He appears to the apostles behind locked doors: “Peace be unto you… do not be afraid.”',
			10: 'Jesus breathes on them and gives them the power to forgive sin.',
		},
		2: {
			name: 'The Ascension',
			description:
				'The Second Glorious Mystery – The Ascension of Our Lord into Heaven',
			meditation: 'Hope',
			1: 'Jesus remains on earth forty days after His Resurrection to prove He has truly risen from the dead.',
			2: 'He commissions the apostles to preach the gospel to every creature,\n and promises to be with them forever.',
			3: 'He will not leave them orphans, but will send the Holy Spirit to enlighten and strengthen them.',
			4: 'Jesus proceeds to Mt. Olivet accompanied by His Mother and the apostles and disciples.',
			5: 'Extending His pierced hands over all in a last blessing, He ascends into heaven.',
			6: 'As He ascends a cloud takes Him from their sight.',
			7: 'Jesus ascends to take His place at the right hand of the Father.',
			8: 'What jubilation there must be amid the angels of heaven at the triumphant entry of Jesus.',
			9: 'The wounds in His glorified body are an endless plea before the Father on our behalf.',
			10: 'The disciples leave Mt. Olivet and “return to Jerusalem with great joy.”',
		},
		3: {
			name: 'The Coming of the Holy Spirit',
			description:
				'The Third Glorious Mystery – The Holy Spirit comes upon Mary and the Apostles',
			meditation: 'Love of God',
			1: 'The apostles are gathered in the upper room where Jesus had held the Last Supper.',
			2: 'They are persevering in prayer with Mary the Mother of Jesus.',
			3: 'A sound comes from heaven like the rush of a mighty wind, and it fills the whole house.',
			4: 'The Holy Spirit descends on each of them in the form of tongues of fire.',
			5: 'Filled with the Gifts of the Holy Spirit, they are enlightened and strengthened to spread the Gospel.',
			6: 'Having lost all fear of the Jewish leaders, the apostles boldly preach Christ crucified.',
			7: 'The multitudes are confounded because every man hears them speak in his own tongue.',
			8: 'The Holy Spirit comes upon the Infant Church never to leave it.',
			9: 'That first day Peter goes forth to preach and baptizes three thousand.',
			10: 'The feast of Pentecost is the birthday of the Church, for on that day it begins to grow.',
		},
		4: {
			name: 'The Assumption of the Blessed Virgin Mary',
			description:
				'The Fourth Glorious Mystery – The Assumption of the Blessed Virgin Mary',
			meditation: 'Mary as Our Mother',
			1: 'After the apostles have dispersed, the Blessed Mother goes to live with John, the beloved disciple.',
			2: 'Mary lives many years on earth after the death of Christ.',
			3: 'She is a source of comfort, consolation and strength to the apostles.',
			4: 'As she had nourished the infant Jesus, so she nourishes spiritually the infant Church.',
			5: 'Mary dies, not of bodily infirmity, but is wholly overcome in a rapture of divine love.',
			6: 'Her body as well as her soul is taken up into heaven.',
			7: 'After her burial the apostles go to the tomb and find only fragrant lilies.',
			8: 'Jesus does not permit the sinless body of His Mother to decay in the grave.',
			9: 'Corruption of the body is an effect of original sin from which Mary is totally exempted.',
			10: 'The bodies of all mankind, at the last judgment, will be brought back and united again to the soul.',
		},
		5: {
			name: 'The Coronation of the Blessed Virgin Mary',
			description:
				'The Fifth Glorious Mystery – The Coronation of Mary as Queen of Heaven and Earth',
			meditation: 'Mary as Our Queen and Lady',
			1: 'As Mary enters heaven, the entire court of heaven greets with joy this masterpiece of God’s creation.',
			2: 'Mary is crowned by her divine Son as Queen of heaven and earth.',
			3: 'More than we can ever know the Hearts of Jesus and Mary overflow with joy at this reunion.',
			4: 'Only in heaven will we know the great majesty of that coronation,\n and the joy it gave to the angels and saints.',
			5: 'Even the angels, who by nature are greater than humans, hail Mary as their Queen.',
			6: 'Mary shares so fully in the glory of Christ because she shared so fully in His suffering.',
			7: 'Only in heaven will we see how central is the role of Mary in the divine plan of redemption.',
			8: 'The angels and saints longed for the coming of her whose heel crushes the head of the serpent.',
			9: 'Mary pleads our cause as a most powerful Queen and a most merciful and loving Mother.',
			10: 'A great sign appeared in heaven; a woman clothed with the sun,\n the moon under her feet, and on her head a crown of twelve stars.',
		},
	},
	Luminous: {
		1: {
			name: 'The Baptism of Jesus',
			description: 'The First Luminous Mystery – The Baptism of the Lord',
			meditation: 'Gratitude for the Gift of Faith',
			1: 'John is baptizing in the Jordan proclaiming a baptism of repentance.',
			2: '“I am the voice of one crying in the desert, make straight the way of the Lord.”',
			3: '“One mightier than I is coming after me.”',
			4: '“I have baptized you with water, He will baptize you with the Holy Spirit.”',
			5: 'Seeing Jesus, John exclaims: “Behold the Lamb of God.”',
			6: 'Against protests of his unworthiness, John baptizes Jesus in the Jordan.',
			7: 'After Jesus’ baptism a voice from Heaven: “This is my beloved Son in whom I am well pleased.”',
			8: 'The Spirit descends upon Jesus in the form of a dove.',
			9: 'In this heavenly manifestation is instituted the sacrament of baptism.',
			10: 'The divine Trinity is manifested: the voice of the Father is heard as the Spirit descends upon the Son.',
		},
		2: {
			name: 'The Wedding in Cana',
			description: 'The Second Luminous Mystery – The Wedding in Cana',
			meditation: 'Fidelity',
			1: 'Jesus, His Mother and disciples were invited to a wedding in Cana.',
			2: 'During the wedding feast the wine ran short.',
			3: 'Mary turned to Jesus: “They have no wine.”',
			4: 'Jesus replied: “What would you have Me do? My hour has not yet come.”',
			5: 'Mary said to the waiters: “Do whatever He tells you.”',
			6: 'There were six stone water jars, each holding fifteen to twenty gallons.',
			7: 'Jesus bids the waiters to fill the jars with water,\n and then draw some out and take it to the chief steward.',
			8: 'The chief steward said to the groom:\n “Every man serves the good wine first… but you have saved the good wine until now.”',
			9: 'At Mary’s request, Jesus worked His first miracle.',
			10: 'By His presence, Christian marriage was raised to the dignity of a Sacrament.',
		},
		3: {
			name: 'The Proclamation of the Kingdom of God and the call to conversion',
			description:
				'The Third Luminous Mystery – The Proclamation of the Kingdom of God and the call to conversion',
			meditation: 'Christian Witness',
			1: '“Repent, for the kingdom of God is at hand.”',
			2: '“My kingdom is not of this world.”',
			3: '“Unless a man be born again of water and the Spirit, he cannot enter the kingdom of heaven.”',
			4: '“Whoever does not accept the kingdom of God as a little child will not enter into it.”',
			5: '“I have come to call sinners, not the just.”',
			6: '“Love your enemies, pray for those who persecute you.”',
			7: '“Blessed are the poor in spirit, for theirs is the kingdom of heaven.”',
			8: '“Blessed are they who hunger and thirst for justice, for they shall be satisfied.”',
			9: '“Blessed are they who suffer persecution for justice’ sake, for theirs is the kingdom of heaven.”',
			10: '“You are Peter, and upon this rock I will build My church…\n I will give you the keys of the kingdom of heaven.”',
		},
		4: {
			name: 'The Transfiguration',
			description: 'The Fourth Luminous Mystery – The Transfiguration',
			meditation: 'Spiritual Courage',
			1: 'Jesus took Peter, James and John up a high mountain to pray.',
			2: 'Jesus was transfigured before them.',
			3: '“His face became as dazzling as the sun, his clothes as radiant as light.”',
			4: 'This was to fortify their faith to withstand the coming tragedy of the Passion.',
			5: 'Jesus foresaw the ‘scandal of the cross,’ and prepared them for it by this manifestation of His glory.',
			6: 'Moses and Elias (representing the Law and the prophets of the Old Testament)\n were conversing with Jesus about His Passion.',
			7: '“Do not think I have come to destroy the Law or the Prophets… but to fulfill them.”',
			8: 'From a cloud came a voice: “This is my beloved Son, listen to Him.”',
			9: 'Jesus admonishes them not to tell the vision to anyone until the Son of Man rises from the dead.',
			10: 'We too will behold the transfigured Jesus on the Last Day.',
		},
		5: {
			name: 'The Institution of the Eucharist',
			description:
				'The Fifth Luminous Mystery – The Institution of the Eucharist',
			meditation: 'Love of Our Eucharistic Lord',
			1: 'I have eagerly desired to eat this Passover with you before I suffer.',
			2: 'Jesus took bread, blessed it: “Take and eat, this is My Body.”',
			3: 'Taking the wine: “This cup is the new covenant in my Blood, shed for you.”',
			4: 'At that eucharistic meal, Jesus celebrated the first Mass.',
			5: 'At every Mass the sacrifice of Calvary is made present.',
			6: 'At the Last Supper Jesus instituted the sacrament of Holy Orders to perpetuate this sacrifice.',
			7: '“Whoever eats my flesh and drinks my blood remains in me and I in him.”',
			8: 'The Eucharist is a sacrifice inasmuch as it is offered up, and a sacrament inasmuch as it is received.',
			9: 'In the Mass we offer ourselves to God, and God gives himself to us.',
			10: 'The Mass will be fruitful in the measure of our surrender to the Father.',
		},
	},
};
